version: '2.4'

services:
    prod_traefik:
        image: traefik
        networks:
         - default
        restart: always
        ports:
          - "80:80"
          - "8080:8080"

        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - ./traefik.toml:/traefik.toml
        container_name: prod_traefik
networks:
  default:
    external: 
      name: gateway

