version: '2.4'

services:
    prod_redis:
      image: redis

    prod_server:
      volumes:
              - /var/log/lighttag/prod:/logs
      environment:
              - LOGFILE_PATH=/logs/log.jsonl
      networks:
                 - default
      extends:
        file: server.yml
        service: server_base
      depends_on: 
        - prod_redis
        - prod_suggestions

      labels:
                - "traefik.http.services.prod-server.loadbalancer.server.port=8000"
                - "service=backend"
                - "traefik.http.routers.prod-server.rule=HostRegexp(`{host:.+}.lighttag.io`) && PathPrefix(`/api`)"
                - "traefik.http.routers.prod-server.priority=142"
                - "traefik.weight=10"
                - "traefik.enable=true"


    prod_suggestions:

      extends:
        file: server.yml
        service: server_base
      command: "./docker_start_suggestions.sh"

    prod_celery:
      depends_on: 
        - prod_redis
      extends:
        file: server.yml
        service: server_base
      command: "./docker_start_celery.sh"

    prod_frontend:
        image: 052831428797.dkr.ecr.us-east-1.amazonaws.com/lt_frontend:prod
        networks:
                 - default
        labels:
                 - "traefik.http.services.prod-frontend.loadbalancer.server.port=5000"
                 - "traefik.enable=true"
                 - "traefik.http.routers.prod-fronted.rule=HostRegexp(`{host:.+}.lighttag.io`) && PathPrefix(`/`)"
                 - "traefik.http.routers.prod-frontend.priority=102"
                 - "traefik.http.middlewares.prod-frontend-replacepath.replacepath.path=/"

networks:
  default:
    external: 
      name: gateway
